---
linters:
    enable-all: true
    disable:
      - gochecknoglobals
      - gochecknoinits
      - lll
      - wsl
      - gomnd
      - gofumpt
      - paralleltest
      - exhaustivestruct
      - testpackage
      - forbidigo

issues:
    max-issues-per-linter: 0
    max-same-issues: 0
    exclude-rules:
      - path: _test\.go
        linters:
          - funlen
